### ISSUE TITLE
Permission Denied letsencrypt.conf

### ISSUE THREAD

**Issue by GesJeremie** [dokku/dokku-letsencrypt#108]
I just followed the README and when I try to run: 

```
$ dokku letsencrypt babysitting
```

I get that:

> =====> Let's Encrypt babysitting
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
Digest: sha256:398e9173f8e9662df66cb6d0dfa6c6ac07f1e3d65b7994177d487d36eb9b10be
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for babysitting...
/var/lib/dokku/plugins/enabled/letsencrypt/subcommands/default: line 24: /home/dokku/babysitting/nginx.conf.d/letsencrypt.conf: Permission denied

I tried to run with sudo, same stuff. 

From what I saw, the file mentioned (letsencrypt.conf) isn't on my system:

> root@dokku:/home/dokku/babysitting/nginx.conf.d# ls -la
total 16
drwxr-xr-x 2 root  root  4096 Feb  2 22:59 .
drwxr-xr-x 9 dokku dokku 4096 Apr  8 08:14 ..
-rw-r--r-- 1 root  root    78 Dec 10 23:33 storage.conf
-rw-r--r-- 1 dokku dokku   25 Feb  2 22:59 upload.conf

**Comment by GesJeremie** [comment]
At the end, I just created the file missing (letsencrypt.conf) and chown dokku on it. Re-ran the command, it worked :p

**Comment by josegonzalez** [comment]
This directory - `/home/dokku/babysitting/` is owned by root, and thats the issue at hand. It should be owned by `dokku:dokku`.

**Comment by nhevia** [comment]
I think creating nginx.conf.d/ folder is pretty common for custom persistent directives, since tweeking per app basis (instead of /etc/nginx) is simpler. And since this folder is not created by default and ssh default user is root, this issue might be present in many projects (configuring nginx before setting SSL certs).

@josegonzalez Do you think it'd be worth to create an empty nginx.conf.d/ on app deployment, to have dokku being the owner by default?

**Comment by josegonzalez** [comment]
Sure, that seems like a good idea (create the directory on app creation). Mind filing an issue/pull request upstream?
