### ISSUE TITLE
Not IPV6 compatible

### ISSUE THREAD

**Issue by jvgreenaway** [dokku/dokku-letsencrypt#139]
I have been having issues using this plugin getting timeout errors in the ACME report. When I removed the AAAA for the domain everything started working. Is the ACME proxy not listing for IPV6?

**Comment by josegonzalez** [comment]
The acme proxy is a local proxy, and has nothing to do with ipv6 or not. If your application or server is not listening to IPv6 properly, then the request will never be received by the plugin.

For reference, it injects the following template into the overall nginx configuration: https://github.com/dokku/dokku-letsencrypt/blob/master/templates/letsencrypt.conf.sigil

Hope that helps. Let me know if you found a workaround or think my closing this issue is in error.
