### ISSUE TITLE
Support adding certs to plugins and not only apps

### ISSUE THREAD

**Issue by ebreton** [dokku/dokku-letsencrypt#155]
Would it be possible to add support for plugins (not only apps)?

The use case I stumbled upon was for grafana, in particular with this issue : https://github.com/dokku/dokku-graphite-grafana/issues/18

**Comment by chrismessiah** [comment]
This feature has many use-cases. Another example is dokku/dokku-postgres#123 (replace the self-signed certificates of remote db connections).

**Comment by raminious** [comment]
any news or progress?

**Comment by josegonzalez** [comment]
No news is good news?

If this hasn't been worked on, it's either due to lack of time on the maintainer's side or lack of desire/need. While others may need this (and other!) functionality, as a maintainer, I don't, so I haven't had a need to implement this, and therefore haven't done any work here.

That said, the project would _love_ to have your input on this and other issues. We have a lovely contributing guide [here](https://github.com/dokku/.github/blob/master/CONTRIBUTING.md). Aside from pull requests, you may also sponsor the work as documented [here](https://github.com/dokku/.github/blob/master/SPONSORING.md) in the case where you either also don't have time or capability, but the functionality is required for business reasons.

Hope that helps :)

**Comment by ebreton** [comment]
I think I can close it... there is no need to have it idling two more years, and the path to follow is clear (thanks @josegonzalez )
