### ISSUE TITLE
Use dokku-letsencrypt for existing backend on the same server

### ISSUE THREAD

**Issue by ivanmonteiro** [dokku/dokku-letsencrypt#201]
Is it possible to use this plugin with an "empty" app?
For exemple, I have one backend on my server running on port 8080 and I also have dokku on the same server used for other apps.
But I would like to create an empty dokku app just so dokku can proxy the requests to my backend and use the dokku letsencrypt plugin for https for my backend.
Is it possible?

**Comment by josegonzalez** [comment]
At this time, the Dokku app needs to be deployed for anyone to add SSL to the application. Adding this functionality is not on the roadmap for the plugin or dokku core.

If you wish to contibute the functionality, that would be great. Otherwise, you may wish to consider [sponsoring the work](https://github.com/dokku/.github/blob/master/SPONSORING.md).
