### ISSUE TITLE
Certificates for redirect domains

### ISSUE THREAD

**Issue by stepin** [dokku/dokku-letsencrypt#21]
I'm using dokku redirect plugin (https://github.com/dokku/dokku-redirect). Redirect domain names should be added to certificate for correct https redirects (for example, https://www.example.net to https://example.com). Plugin stores domains in the $APP/REDIRECTS file.

Workaround:
1) add redirect domains using "dokku domains:add"
2) issue certificate ("dokku letsencrypt")
3) remove redirect domains to fix nginx config ("dokku domains:clear")
4) add non-redirect domains using "dokku domains:add" (if you need more than 1)

**Comment by sseemayer** [comment]
I've had a look at this for a bit -- when requesting a certificate for additional domains in the ACME request, the let's encrypt server will accept these but verification will fail because the nginx server is configured to redirect everything under that address to whatever the redirect points to.

Probably, this will require temporarily disabling the redirect during certificate request and instead adding domains as mentioned in your workaround so that the domain validation will succeed.

**Comment by sseemayer** [comment]
After a further look at this, I don't think it's possible to do this without temporarily removing the redirects from the app, causing a possible unavailability of redirects during certificate renewal. Since zero-downtime is one of the goals of the plugin, I'll unfortunately not be able to provide this functionality - sorry :disappointed:

**Comment by sseemayer** [comment]
This shouldn't stop you from automating your renewal by putting the workaround you described into a shell script, though.

**Comment by sseemayer** [comment]
Since there was renewed interest in this by @praveenperera and because of the discussion on the dokku/dokku-redirect#1 issue, I've decided to write up what the technical problem is exactly from the dokku-letsencrypt perspective. cc @marvinroger so we can maybe re-visit this.

Say we have an app reachable at `http://myapp.com` with an additional redirect set up to redirect from `http://www.myapp.com` to `http://myapp.com` using the dokku/dokku-redirect plugin. Why don't we simply request a let's encrypt certificate for all app domains listed in `dokku domains myapp` (as we currently do) PLUS the redirection source addresses of the dokku-redirect plugin?

The redirect plugin will redirect ALL requests that match the source definition to whatever the destination is and there currently is no mechanism to not redirect chosen subdirectories. Depending on what the destination of the redirect is, we have two scenarios:

a) The destination of the redirect points back to another valid URL for your app (this is @praveenperera 's situation). The ACME validation request at `http://www.myapp.com/.well-known/acme-challenge/xxxxxxx` will get redirected by the plugin to `http://myapp.com/.well-known/acme-challenge/xxxxxxx` which is a valid alternate URL for the same resource and validation succeeds because we're proxying the ACME request to the standalone authenticator.

b) The user can also use the redirect plugin to redirect to another website that is not part of the same dokku app, let's say `http://anotherapp.com/.well-known/acme-challenge/xxxxxxx`. Since the letsencrypt plugin has no way to intercept the redirection before it happens, it will not be able to handle the ACME validation requests coming in and validation will fail if the other URL cannot complete the request.

Because b) is a possible use case for the redirect plugin, adding the list of redirection sources to the list of domains we request certificates for will make the validation fail with no certificate being signed. Instead of the current workaround of having to add and remove domains for the app, the new workaround would be then to

- remove the redirect
- add the redirect source as a temporary domain
- run letsencrypt
- remove the temporary domain and then 
- re-add the redirect

Neither the current nor this alternative workaround are zero-downtime which is why I've decided to not automate the workaround as part of this zero-downtime plugin.

Alternatively, we could check whether a redirect is a type-a or type-b redirect and only add all type-a redirects to the list of requested domain names. That would mean that we will not be able to listen on HTTPS for a b-type redirect source. Also, how would we reliably differentiate between type-a and type-b redirects?

Does anyone have other ideas of how we can make this work?

**Comment by marvinroger** [comment]
> Neither the current nor this alternative workaround are zero-downtime which is why I've decided to not automate the workaround as part of this zero-downtime plugin.

Maybe this behavior can be configurable via a dokku command?

> Alternatively, we could check whether a redirect is a type-a or type-b redirect and only add all type-a redirects to the list of requested domain names.

Good idea, I guess most users set type-a redirects anyway.

> how would we reliably differentiate between type-a and type-b redirects?

Simply by checking if the redirect destination is part of the app domains, no?
