### ISSUE TITLE
Let's Encrypt certificates are not obtained for cloned apps (HTTPS is not preserved)

### ISSUE THREAD

**Issue by gleniat** [dokku/dokku-letsencrypt#265]
## Description of problem
Cloning an app doesn't preserve HTTPS setting – Let's Encrypt certificates are not obtained for cloned apps automatically.

### How reproducible
Always, easily.

### Steps to Reproduce
1. Let's have an app `myapp` available from `https://myapp.mydomain.com`
Let's Encrypt was enabled for this app earlier (`dokku letsencrypt:enable myapp`).
3. `dokku apps:clone myapp myapp-pr-10`

#### Actual Results
`myapp` is available from `https://myapp.mydomain.com` (HTTPS)
`myapp-pr-10` is published on `http://myapp-pr-10.mydomain.com` (HTTP only)

#### Expected Results
`myapp` is available from `https://myapp.mydomain.com` (HTTPS)
`myapp-pr-10` is published on `https://myapp-pr-10.mydomain.com` (**HTTPS**)

### Environment Information
[dokku v0.27.4](https://github.com/dokku/dokku/releases/tag/v0.27.4)
[dokku-letsencrypt v0.12.1](https://github.com/dokku/dokku-letsencrypt/releases/tag/0.12.1)
[dokku-github v1.0.2](https://github.com/dokku/github-action/releases/tag/v1.0.2)

### How and where was Dokku installed?:
deb, physical debian PC

### Additional information
[Dokku github action](https://github.com/dokku/github-action) has the same issue when using its `review-apps:create` command to create a review app automatically. It also uses `dokku apps:clone` command under the hood to create the review app. Let's Encrypt certificate is not obtained for a new app.

If this is the desired behavior, I'd like to know how to enable Let's Encrypt for all newly created clones of the app, or globally for all newly created apps.

Thank you!

**Comment by Gys** [comment]
This might answer your question: https://github.com/dokku/dokku-letsencrypt/issues/287#issuecomment-1326707574

**Comment by josegonzalez** [comment]
This is desired behavior. The ssl certificate isn't copied because the domain of the new app won't match the old one. We also don't have functionality to auto-set letsencrypt for new apps, and I don't want to build that functionality.

For anyone using our CI integrations, you can create a `bin/ci-pre-deploy` in your repository. The CI integrations will execute that on deploy, and you can use it to enable letsencrypt on your app (or do any other configuration). An example is [here](https://github.com/dokku/github-action/blob/master/example-workflows/review-app/ci-pre-deploy).
