### ISSUE TITLE
Conflict with dokku-http-auth

### ISSUE THREAD

**Issue by johnfraney** [dokku/dokku-letsencrypt#34]
LetsEncrypt is unable to verify a domain behind http authentication. Since dokku-http-auth is an official plugin, it might be good to find a way to get these plugins to work together. If not, we can always add a note in the documentation that dokku-http-auth has to be disabled for this plugin to work correctly.

Here's the dokku output when trying to add letsencrypt to an app with http-auth turned on: https://gist.github.com/johnfraney/62b1dc5ccddd2c8a7358

**Comment by sseemayer** [comment]
I brought this up in #3 back when dokku-letsencrypt wasn't official yet but you're right that that discussion should be re-opened. Let's do this!

**Comment by sseemayer** [comment]
Here's a short breakdown of what is going on at the moment:

- When activating http-auth, the plugin uses [this template](https://github.com/dokku/dokku-http-auth/blob/master/templates/http-auth.conf) to put a config into `$APP_ROOT/nginx.conf.d`.
- When using the `dokku letsencrypt` command, we use [this template](https://github.com/dokku/dokku-letsencrypt/blob/master/templates/letsencrypt.conf) to put a config into `$APP_ROOT/nginx.conf.d` to temporarily enable a reverse proxy to the ACME authenticator.
- The [nginx template will include all `.conf` files in `nginx.conf.d` in the `server` section of the app's nginx config](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/location.config#L20)
- Since both configuration files are included at the same level in hierarchy, they both will become active - we get a reverse proxy for the `.well-known/acme-challenge` path, but it will be password-protected.

**Comment by sseemayer** [comment]
Derp, as always, [googling the problem helps](http://serverfault.com/a/330592)

**Comment by johnfraney** [comment]
Nice work!
