### ISSUE TITLE
One certificate per domain in app

### ISSUE THREAD

**Issue by klenis** [dokku/dokku-letsencrypt#48]
Hi!

First of, nice work on this plugin. Works beautifully!

As I understand it, the current solution is to create one certificate for all domains in an app. Are there any plans on supporting the creation of one certificate per domain in an app? This would be really helpful in some cases.

Thanks!

**Comment by sseemayer** [comment]
Thanks for your interest in the plugin!

You understand correctly that dokku-letsencrypt requests one certificate for all app domains because [that is how certificate management in dokku is designed](http://dokku.viewdocs.io/dokku/deployment/ssl-configuration/). You would have to implement an alternative solution to dokku certificate management before separate certficates per domain can be added to dokku-letsencrypt.

If you want to have separate certificates for different domains right now, you could either 

a) run each domain in a separate app or 
b) it might also be possible to do this with creating a [custom nginx config](http://dokku.viewdocs.io/dokku/nginx) for the app using several 'server' blocks and configuring separate certificate paths for them. You'd have to write your own certificate retrieval procedure then, though.
