### ISSUE TITLE
nginx.conf has no ssl section

### ISSUE THREAD

**Issue by MichaelSp** [dokku/dokku-letsencrypt#69]
With current version (letsencrypt 0.8.3; dokku 0.6.5) The generated <app>/nginx.conf is missing the ssl section.

```
# dokku letsencrypt app
=====> Let's Encrypt app
-----> Updating letsencrypt docker image...
latest: Pulling from dokkupaas/letsencrypt-simp_le
420890c9e918: Already exists 
e4a2ae244258: Already exists 
5c6ac6d1c950: Already exists 
Digest: sha256:18a19b34beceba79dd5be458abe7e132fc7486da1da19cc4d0395ad4578031ef
Status: Image is up to date for dokkupaas/letsencrypt-simp_le:latest
       done updating
-----> Enabling ACME proxy for app...
-----> Getting letsencrypt certificate for app...
        - Domain 'app.example.com'
darkhttpd/1.11, copyright (c) 2003-2015 Emil Mikulic.
listening on: http://0.0.0.0:80/
2016-07-08 18:08:14,629:INFO:__main__:1211: Generating new account key
2016-07-08 18:08:15,214:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2016-07-08 18:08:15,463:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2016-07-08 18:08:15,714:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2016-07-08 18:08:16,323:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): letsencrypt.org
2016-07-08 18:08:16,945:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2016-07-08 18:08:17,207:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2016-07-08 18:08:17,465:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): app.example.com
2016-07-08 18:08:17,516:INFO:__main__:1305: app.example.com was successfully self-verified
2016-07-08 18:08:17,529:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2016-07-08 18:08:17,772:INFO:__main__:1313: Generating new certificate private key
2016-07-08 18:08:18,997:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2016-07-08 18:08:19,250:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2016-07-08 18:08:19,545:INFO:requests.packages.urllib3.connectionpool:758: Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2016-07-08 18:08:19,789:INFO:__main__:391: Saving account_key.json
2016-07-08 18:08:19,790:INFO:__main__:391: Saving fullchain.pem
2016-07-08 18:08:19,790:INFO:__main__:391: Saving chain.pem
2016-07-08 18:08:19,790:INFO:__main__:391: Saving cert.pem
2016-07-08 18:08:19,790:INFO:__main__:391: Saving key.pem
-----> Certificate retrieved successfully.
-----> Symlinking let's encrypt certificates
-----> Unsetting app
-----> Unsetting DOKKU_PROXY_PORT_MAP
-----> Setting config vars
       DOKKU_PROXY_PORT_MAP: http:80:80
-----> Configuring app.example.com...(using built-in template)
-----> Creating https nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Configuring app.example.com...(using built-in template)
-----> Creating https nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Disabling ACME proxy for app...
       done
```
```
# cat nginx.conf
server {
  listen      [::]:80;
  listen      80;
  server_name app.example.com; 
  access_log  /var/log/nginx/app-access.log;
  error_log   /var/log/nginx/app-error.log;

  return 301 https://$host:$request_uri;

}

upstream app-80 {

  server 172.17.0.10:80;
}
```

**Comment by sseemayer** [comment]
I'm assuming that you and @samuelcolvin (posted in #68) are having a similar issue and I will debug this here since it includes more information to start with.

It looks like the `DOKKU_PROXY_PORT_MAP` and `DOKKU_NGINX_SSL_PORT` variables are [not set correctly to include the SSL port](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/functions#L83-L93) which seems to be due to some configuration problem. Can you please let me know:

- Is this a herokuish or Dockerfile deployment?
- The output of `dokku config yourapp`
- The output of `dokku certs:info yourapp`
- The output of `dokku proxy:ports yourapp`

**Comment by samuelcolvin** [comment]
See https://github.com/dokku/dokku/issues/2307 for details on my setup
having the same problem in #68.

**Comment by MichaelSp** [comment]
I found the problem. Somehow there was a 301 redirect to https in the nginx.conf that persisted app rebuild.
```   return 301 https://$host:$request_uri; ``` 
removed that line; `service nginx reload` and `dokku letsencrypt app`
Now it's working. Thanks for your help.

**Comment by MichaelSp** [comment]
Problem is back :(

Here are the infos:
It's a Dockerfile-deployment

```
# dokku config mywp
=====> mywp config vars
DATABASE_URL:                mysql://mysql:<PWD>@dokku-mysql-mywp:3306/mywp
DOKKU_APP_RESTORE:           1
DOKKU_APP_TYPE:              dockerfile
DOKKU_DOCKERFILE_CMD:        CMD ["apache2-foreground"]
DOKKU_DOCKERFILE_ENTRYPOINT: ENTRYPOINT ["/entrypoint.sh"]
DOKKU_DOCKERFILE_PORTS:      80/tcp
DOKKU_LETSENCRYPT_EMAIL:     ms@example.com
DOKKU_PROXY_PORT_MAP:        http:80:80
root@host:/home/dokku/mywp# dokku certs:info mywp
do-----> Fetching SSL Endpoint info for mywp...
-----> Certificate details:
=====> Common Name(s): 
=====>    mywp.example.com
=====>    mywp.other-domain.com
=====>    mywp.example.com
=====> Expires At: Oct 10 08:14:00 2016 GMT
=====> Issuer: C=US, O=Lets Encrypt, CN=Lets Encrypt Authority X3
=====> Starts At: Jul 12 08:14:00 2016 GMT
=====> Subject: CN=mywp.example.com
=====> SSL certificate is self signed.
root@host:/home/dokku/mywp# dokku proxy:ports mywp
-----> Port mappings for mywp
-----> scheme             host port                 container port                                     
http                      80                        80                                                 
```

**Comment by chrisnew** [comment]
I got a similar issue recently… However, when I add `https` to `DOKKU_PROXY_PORT_MAP` manually, it’s working well.

**Comment by sseemayer** [comment]
It seems like [the way that dokku handles proxying of Dockerfile deploys](http://dokku.viewdocs.io/dokku/advanced-usage/proxy-management/#proxy-port-mapping) since 0.6 and how this relates to dokku-letsencrypt is not clear so I should clarify:

The dokku-letsencrypt plugin only handles certificate installation and leaves nginx configuration to the underlying dokku mechanisms. In the case of the Dockerfile deploy, this means that the reverse proxy will have to be configured correctly by the user using the `dokku proxy:ports-*` commands since by default, only `EXPOSE` directives in the Dockerfile will be parsed to forward exposed ports in the Docker containre to the same port numbers on the host. This means that both the forwards for HTTP port 80 and HTTPS port 443 to the app's container needs to be manually configured for certificate validation and browsing to the app via HTTPS to work.

A full workflow for deploying a new Dockerfile deployment with dokku-letsencrypt would be:

1. Create a new app `myapp` in dokku and push to the `dokku@myhost.com` remote. I assume that the Docker container will be listening for connections on port 5555.
2. On the dokku host, use `dokku proxy:ports-add myapp http:80:5555` to proxy http port 80 to port 5555 on the Docker image
3. On the dokku host, use `dokku letsencrypt myapp` to retrieve HTTPS certificates.
4. On the dokku host, use `dokku proxy:ports-add myapp https:443:5555` to proxy https port 443 to port 5555 on the Docker image
5. (optional) On the dokku host, use `dokku proxy:ports-remove myapp http:5555:5555` to remove a potential leftover port forward that was automatically configured on first deploy.

After this, the output of `dokku proxy:ports myapp` should look like this:
```
-----> Port mappings for myapp
-----> scheme             host port                 container port                                     
http                      80                        5000                                               
https                     443                       5000  
```

As @chrisnew mentioned, it is possible to change `DOKKU_PROXY_PORT_MAP` manually but I'd recommend the official proxy plugin API.

Step 2 and step 4 cannot be joined together since a configured HTTPS proxy will automatically create a HTTP 301 redirect to the HTTPS address that will fail because no valid HTTPS certificate is available until step 3 completed.

**Comment by blocka** [comment]
Worth adding this to the readme...

**Comment by chrisnew** [comment]
@sseemayer Thanks for the clarification! `dokku proxy:ports-add` was completely new to me until now. Thanks again!

**Comment by MichaelSp** [comment]
Thanks @sseemayer Your steps worked for me, but I still hope to have the `dokku letsencrypt`-command as a 0-brainer, with no additional configuration. Is that feasible?

**Comment by sseemayer** [comment]
I agree that it is good idea to add documentation on Dockerfile deploys to the dokku-letsencrypt README. Added with c1840405fbc99b3b791bc4e39218bf5f20814774.

The additional steps required to make Dockerfile deploys work like herokuish deploys exist not so much because of dokku-letsencrypt but because of the additional flexibility of Dockerfile deploys combined with how the dokku API for Dockerfile deploys is designed. 

For me the current workflow seems "good enough" since configuration only needs to be done once per app and [Dockerfile deploys are considered a power user feature by the dokku project](http://dokku.viewdocs.io/dokku/deployment/methods/dockerfiles/#dockerfile-deployment). If any of you have suggestions on how to streamline this, I'd be open to discuss, though!

**Comment by sseemayer** [comment]
Also note that proxy configuration will be simplified with dokku/dokku#2317

**Comment by sseemayer** [comment]
Closing since dokku/dokku#2317 was merged and there were no more suggestions.
