### ISSUE TITLE
Plugin does not work for .io domains

### ISSUE THREAD

**Issue by schmoofer** [dokku/dokku-letsencrypt#71]
Plugin does not seem to work for .io domains. I'm getting a 404 after going through the setup process. Going through the same process for other domain extensions like .net, .com, and .org had no problems.

**Comment by sseemayer** [comment]
I'm currently in the process of preparing a move so I might take a while longer to respond.

Can you please provide your app's `nginx.conf` from `/home/dokku/appname/nginx.conf` ?

What is the output of `dokku urls appname`?

Is there a 404 error on the HTTP (port 80) link too, or is it just after HTTP redirects to the HTTPS address?

**Comment by schmoofer** [comment]
HTTP does redirect to the HTTPS address.

nginx.conf:

```
server {
  listen      [::]:80;
  listen      80;
  server_name elocute.io www.elocute.io elocute.euphonialabs.com; 
  access_log  /var/log/nginx/elocute-access.log;
  error_log   /var/log/nginx/elocute-error.log;

  return 301 https://$host:443$request_uri;

}

server {
  listen      [::]:443 ssl http2;
  listen      443 ssl http2;
  server_name elocute.io www.elocute.io elocute.euphonialabs.com; 
  server_name elocute.io www.elocute.io elocute.euphonialabs.com; 
  access_log  /var/log/nginx/elocute-access.log;
  error_log   /var/log/nginx/elocute-error.log;

  ssl_certificate     /home/dokku/elocute/tls/server.crt;
  ssl_certificate_key /home/dokku/elocute/tls/server.key;

  keepalive_timeout   70;
  

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://elocute-5000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/elocute/nginx.conf.d/*.conf;
}

upstream elocute-5000 {

  server 172.17.0.7:5000;
}
```
Output of `dokku urls elocute`:

```
http://elocute.euphonialabs.com
http://elocute.io
https://elocute.euphonialabs.com
https://elocute.io
https://www.elocute.io
http://www.elocute.io
```

**Comment by sseemayer** [comment]
Both the `nginx.conf` and the output of `dokku urls eloclute`  look good to me.

When I try to curl the .io address, I get into a redirection loop:

http://www.elocute.io `-- HTTP 301 -->` https://www.elocute.io `-- HTTP 301 -->` http://www.elocute.io `--HTTP 301 -->` ...

Also, the domain seems to be served by CloudFlare so I think you're having a CloudFlare configuration problem rather than a problem with dokku-letsencrypt.

You could check the nginx access and error logs to see if the requests reach the dokku server and to troubleshoot.

**Comment by mwerner** [comment]
I've used this plugin successfully on an `.io` domain. No problems at all.

**Comment by schmoofer** [comment]
You're right. Disabling Cloudflare did resolve the issue. However, this seems to only affect .io domains (as far as I know). I haven't had to disable Cloudflare for my other apps with .org, .net, and .com extensions. For example, my app at https://euphoniatalks.com/ is using Cloudflare and secured by Let's Encrypt, and it was set up identically (also using Dokku).

**Comment by sseemayer** [comment]
Since dokku-letsencrypt works for .io domains (thanks for the confirmation @mwerner) and I don't see how .io domains would be different than other TLDs (I run dokku successfully on a .de domain which is also a two-letter TLD),  I think this is not a bug in dokku-letsencrypt but a configuration problem of your app, web server or CloudFlare. To debug this, I'd suggest to trace the HTTP requests using something like `curl -v` and looking at the web server logs. Sorry I can't help you further  :disappointed:
