### ISSUE TITLE
Support for --expand option

### ISSUE THREAD

**Issue by jimthedev** [dokku/dokku-letsencrypt#75]
Sometimes I'll have a main droplet at example.com and a secondary droplet at users.example.com (running dokku). If I want separate LE certs for example.com and users.example.com apparently it is possible using `--expand`. Any chance you'd have some guidance on enabling this option so that we could support this kind of configuration? 

Thanks for your help!

**Comment by jimthedev** [comment]
More info on --expand here: http://letsencrypt.readthedocs.io/en/latest/using.html

**Comment by sseemayer** [comment]
dokku-letsencrypt does not use the certbot Let's Encrypt client but rather the [simp_le](https://github.com/kuba/simp_le) client since it is easier to automate. As far as I know, simp_le unfortunately doesn't support the `--expand` feature. Additionally, the dokku-letsencrypt configuration system will always request a new certificate once the domain list or some other settings have changed. 

The two factors combined make it quite challenging to implement this feature in dokku-letsencrypt - sorry :disappointed:

**Comment by sseemayer** [comment]
I'm not sure if I understand your use case, though. You have a dokku app on host A listening only on users.example.com and another host B listening only on example.com? Then you can simply do the following:

1. Configure your DNS to point users.example.com to point to host A and example.com to host B
2. Use any mechanism to retrieve a certificate only for `example.com` on host B and install it to the web server there
3. Use dokku-letsencrypt to retrieve a certificate only for `users.example.com` on host A and automatically install it to dokku
