### ISSUE TITLE
server_name duplication

### ISSUE THREAD

**Issue by leshik** [dokku/dokku-letsencrypt#76]
Hi,

I'm not sure if it's letsencrypt plugin issue or not, but I see duplication of server_name directive in application's vhost config for ssl, like this:

```
server {
  listen      [::]:443 ssl http2;
  listen      443 ssl http2;
  server_name domain.com;
  server_name domain.com;
  access_log  /var/log/nginx/domain-access.log;
  error_log   /var/log/nginx/domain-error.log;
...
}
```

If I manually delete it, it persists after restart.

**Comment by leshik** [comment]
I researched a bit and found that this is because `get_ssl_hostnames()` function from [plugins/certs/functions#L17](https://github.com/dokku/dokku/blob/master/plugins/certs/functions#L17) returns all domains of given certificate and letsencrypt certs have same name in CN and alt names section.

**Comment by josegonzalez** [comment]
@leshik what version of dokku are you using?

**Comment by leshik** [comment]
I think that I use latest version:
```
# dokku version
0.6.4
# dokku plugin | grep letsencrypt
  letsencrypt          0.8.5 enabled    Automated installation of let's encrypt TLS certificates
```

**Comment by josegonzalez** [comment]
Do you mind upgrading to 0.7.0? I think I fixed a few issues around our letsencrypt integration in that version.

**Comment by leshik** [comment]
Sure, was it released already? I have this in my sources.list `deb https://packagecloud.io/dokku/dokku/ubuntu/ xenial main` and I can see that the latest available version is 0.6.4.

**Comment by josegonzalez** [comment]
Yes, it was released. You'll want to trigger an `apt-get update`.

**Comment by leshik** [comment]
Oh, sorry, I see now. I've upgraded to xenial recently and thus have non-existent distro name in sources.

**Comment by leshik** [comment]
Anyway, I continue to see server_name duplication in nginx config.

**Comment by sseemayer** [comment]
Sorry to take >2 months to respond to this.

dokku/dokku#2464 should remove cases where the same hostname gets listed twice in the same `server_name` line. 

However, you will still see two `server_name` lines for apps with SSL configured because the [default nginx template](https://github.com/dokku/dokku/blob/master/plugins/nginx-vhosts/templates/nginx.conf.sigil#L43-L44) has one line for SSL hostnames and one line for non-SSL hostnames. Since Dokku lists the app's hostnames in both these conditions, this leads to the duplication.

If this duplication bothers you, you can have a look into [providing a custom nginx.conf template](http://dokku.viewdocs.io/dokku/configuration/nginx/).
